### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by yzfr6** [IHTSDO/openai-demo#4]
The demo available [here](https://ihtsdo.github.io/openai-demo/) mentioned in your project doesn't work. The NLP tool returns an empty table, and the NLPv2 tool loads continuously when executing

**Comment by kaicode** [comment]
Please select the "OpenAI API" tab and enter valid OpenAI credentials in order to try the demos. 
See this help article for more information: https://help.openai.com/en/articles/4936850-where-do-i-find-my-secret-api-key
<img width="185" alt="Screenshot 2023-10-03 at 16 08 04" src="https://github.com/IHTSDO/openai-demo/assets/2010517/b82851bb-27e4-4689-a2e4-b2f90b84139f">

**Comment by yzfr6** [comment]
I have entered valid credentials but I receive the same error. The console log for NLP is as follows:
```
[Error] Failed to load resource: the server responded with a status of 429 () (completions, line 0)
```

and for NLPv2:
```
[Error] ERROR – Error: Uncaught (in promise): Error: Request failed with status code 429
@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1021663
@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1024107
ze@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1016046
We@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:11525
onInvokeTask@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:101387
runTask@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:2601
invokeTask@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:8254
Z@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:20769
N@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:21057
Error: Uncaught (in promise): Error: Request failed with status code 429
@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1021663
@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1024107
ze@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:1016046
We@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:11525
onInvokeTask@https://ihtsdo.github.io/openai-demo/main.8423587d3493de05.js:1:101387
runTask@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:2601
invokeTask@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:8254
Z@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:20769
N@https://ihtsdo.github.io/openai-demo/polyfills.bd8dd0a8407ab546.js:1:21057
	handleError (main.8423587d3493de05.js:1:51402)
	next (main.8423587d3493de05.js:1:107727)
	next
	next (main.8423587d3493de05.js:1:3484)
	_next (main.8423587d3493de05.js:1:3164)
	next (main.8423587d3493de05.js:1:2855)
	(anonymous function) (main.8423587d3493de05.js:1:6016)
	hn (main.8423587d3493de05.js:1:2604)
	next (main.8423587d3493de05.js:1:5851)
	emit (main.8423587d3493de05.js:1:88028)
	run (polyfills.bd8dd0a8407ab546.js:1:1981)
	onHandleError (main.8423587d3493de05.js:1:101879)
	runGuarded (polyfills.bd8dd0a8407ab546.js:1:2161)
	(anonymous function) (polyfills.bd8dd0a8407ab546.js:1:14626)
	_ (polyfills.bd8dd0a8407ab546.js:1:9288)
	invokeTask (polyfills.bd8dd0a8407ab546.js:1:8279)
	Z (polyfills.bd8dd0a8407ab546.js:1:20770)
	N (polyfills.bd8dd0a8407ab546.js:1:21058)
```

**Comment by kaicode** [comment]
> The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").

The 429 error indicates that the OpenAI account you are using may have made too many requests recently.
See [OpenAI: Rate Limits](https://platform.openai.com/docs/guides/rate-limits/overview).

**Comment by yzfr6** [comment]
Ive created new keys within my openai account and still receive the same error. I have created another account and still receive the same error. Tried in multiple browsers too

<img width="1675" alt="image" src="https://github.com/IHTSDO/openai-demo/assets/11949078/15d5d31b-38db-4d5e-831e-bc20334eb34e">

**Comment by kaicode** [comment]
The demo just makes calls to the OpenAI APIs. If you are getting a 429 response then you must be getting blocked by OpenAI. Perhaps they are rate limiting your IP address. I'm not able to help with this.
